const dictionary={
    "id": 77,
    "name": "[Sample] Fog Linen Chambray Towel - Beige Stripe",
    "type": "physical",
    "sku": "SLCTBS",
    "description": "<p>The perfect beach towel: thin, lightweight and highly absorbent. Crafted by Fog Linen in Japan using soft Lithuanian linen, each towel rolls up for compact stowaway. Dry off after a refreshing dip in the ocean and stretch out on it for a sun bath. The thinness ensures a quick dry so you can have it rolled back up in your bag without soaking your belongings.</p>\n<p>Measures 75 x 145 cm/29.5 x 57 in</p>\n<p>100% Linen</p>",
    "weight": 1,
    "width": 0,
    "depth": 0,
    "height": 0,
    "price": 49,
    "cost_price": 0,
    "retail_price": 0,
    "sale_price": 0,
    "map_price": 0,
    "tax_class_id": 0,
    "product_tax_code": "",
    "calculated_price": 49,
    "categories": [
        23,
        18
    ],
    "brand_id": 0,
    "option_set_id": 14,
    "option_set_display": "right",
    "inventory_level": 43,
    "inventory_warning_level": 0,
    "inventory_tracking": "variant",
    "reviews_rating_sum": 0,
    "reviews_count": 0,
    "total_sold": 4,
    "fixed_cost_shipping_price": 0,
    "is_free_shipping": false,
    "is_visible": true,
    "is_featured": false,
    "related_products": [
        -1
    ],
    "warranty": "",
    "bin_picking_number": "",
    "layout_file": "product.html",
    "upc": "",
    "mpn": "",
    "gtin": "",
    "search_keywords": "",
    "availability": "available",
    "availability_description": "",
    "gift_wrapping_options_type": "any",
    "gift_wrapping_options_list": [],
    "sort_order": 0,
    "condition": "New",
    "is_condition_shown": false,
    "order_quantity_minimum": 0,
    "order_quantity_maximum": 0,
    "page_title": "",
    "meta_keywords": [],
    "meta_description": "",
    "date_created": "2015-07-03T17:57:10+00:00",
    "date_modified": "2023-07-25T20:12:43+00:00",
    "view_count": 63,
    "preorder_release_date": null,
    "preorder_message": "",
    "is_preorder_only": false,
    "is_price_hidden": false,
    "price_hidden_label": "",
    "custom_url": {
        "url": "/fog-linen-chambray-towel-beige-stripe/",
        "is_customized": false
    },
    "base_variant_id": null,
    "open_graph_type": "product",
    "open_graph_title": "",
    "open_graph_description": "",
    "open_graph_use_meta_description": true,
    "open_graph_use_product_name": true,
    "open_graph_use_image": true,
    "variants": [
        {
            "id": 1,
            "product_id": 77,
            "sku": "SLCTBS-A9615491",
            "sku_id": 70,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 68,
                    "label": "XS",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 7,
                    "label": "Silver",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 2,
            "product_id": 77,
            "sku": "SLCTBS-5596D19E",
            "sku_id": 71,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 69,
                    "label": "S",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 7,
                    "label": "Silver",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 3,
            "product_id": 77,
            "sku": "SLCTBS-08950B35",
            "sku_id": 72,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 3,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 70,
                    "label": "M",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 7,
                    "label": "Silver",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 4,
            "product_id": 77,
            "sku": "SLCTBS-7765C099",
            "sku_id": 73,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 71,
                    "label": "L",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 7,
                    "label": "Silver",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 5,
            "product_id": 77,
            "sku": "SLCTBS-FC402DAC",
            "sku_id": 74,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 72,
                    "label": "XL",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 7,
                    "label": "Silver",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 6,
            "product_id": 77,
            "sku": "SLCTBS-4404031B",
            "sku_id": 75,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 68,
                    "label": "XS",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 8,
                    "label": "Black",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 7,
            "product_id": 77,
            "sku": "SLCTBS-EBD25EBB",
            "sku_id": 76,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 69,
                    "label": "S",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 8,
                    "label": "Black",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 8,
            "product_id": 77,
            "sku": "SLCTBS-6C6855B4",
            "sku_id": 77,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 70,
                    "label": "M",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 8,
                    "label": "Black",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 9,
            "product_id": 77,
            "sku": "SLCTBS-2C8FBF3C",
            "sku_id": 78,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 71,
                    "label": "L",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 8,
                    "label": "Black",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 10,
            "product_id": 77,
            "sku": "SLCTBS-906CEB57",
            "sku_id": 79,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 72,
                    "label": "XL",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 8,
                    "label": "Black",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 11,
            "product_id": 77,
            "sku": "SLCTBS-B6062BD4",
            "sku_id": 80,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 68,
                    "label": "XS",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 9,
                    "label": "Purple",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 12,
            "product_id": 77,
            "sku": "SLCTBS-5819AF19",
            "sku_id": 81,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 69,
                    "label": "S",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 9,
                    "label": "Purple",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 13,
            "product_id": 77,
            "sku": "SLCTBS-E4DD8E16",
            "sku_id": 82,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 70,
                    "label": "M",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 9,
                    "label": "Purple",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 14,
            "product_id": 77,
            "sku": "SLCTBS-BC2B8DF2",
            "sku_id": 83,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 71,
                    "label": "L",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 9,
                    "label": "Purple",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 15,
            "product_id": 77,
            "sku": "SLCTBS-A588AB27",
            "sku_id": 84,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 1,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 72,
                    "label": "XL",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 9,
                    "label": "Purple",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 16,
            "product_id": 77,
            "sku": "SLCTBS-CCAEAE80",
            "sku_id": 85,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 68,
                    "label": "XS",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 10,
                    "label": "Blue",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 17,
            "product_id": 77,
            "sku": "SLCTBS-AA87E3C9",
            "sku_id": 86,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 69,
                    "label": "S",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 10,
                    "label": "Blue",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 18,
            "product_id": 77,
            "sku": "SLCTBS-7113955F",
            "sku_id": 87,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 70,
                    "label": "M",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 10,
                    "label": "Blue",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 19,
            "product_id": 77,
            "sku": "SLCTBS-AF6BD618",
            "sku_id": 88,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 1,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 71,
                    "label": "L",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 10,
                    "label": "Blue",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 20,
            "product_id": 77,
            "sku": "SLCTBS-3E102384",
            "sku_id": 89,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 72,
                    "label": "XL",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 10,
                    "label": "Blue",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 21,
            "product_id": 77,
            "sku": "SLCTBS-9D20C568",
            "sku_id": 90,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 68,
                    "label": "XS",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 11,
                    "label": "Green",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 22,
            "product_id": 77,
            "sku": "SLCTBS-ADB96FB6",
            "sku_id": 91,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 69,
                    "label": "S",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 11,
                    "label": "Green",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 23,
            "product_id": 77,
            "sku": "SLCTBS-DDB31DBA",
            "sku_id": 92,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 70,
                    "label": "M",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 11,
                    "label": "Green",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 24,
            "product_id": 77,
            "sku": "SLCTBS-1FB01D8C",
            "sku_id": 93,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 1,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 71,
                    "label": "L",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 11,
                    "label": "Green",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 25,
            "product_id": 77,
            "sku": "SLCTBS-15688F0B",
            "sku_id": 94,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 72,
                    "label": "XL",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 11,
                    "label": "Green",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 26,
            "product_id": 77,
            "sku": "SLCTBS-CB178380",
            "sku_id": 95,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 68,
                    "label": "XS",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 12,
                    "label": "Yellow",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 27,
            "product_id": 77,
            "sku": "SLCTBS-E8CD0FC8",
            "sku_id": 96,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 1,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 69,
                    "label": "S",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 12,
                    "label": "Yellow",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 28,
            "product_id": 77,
            "sku": "SLCTBS-E0F9565B",
            "sku_id": 97,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 70,
                    "label": "M",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 12,
                    "label": "Yellow",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 29,
            "product_id": 77,
            "sku": "SLCTBS-AC1B2718",
            "sku_id": 98,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 71,
                    "label": "L",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 12,
                    "label": "Yellow",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 30,
            "product_id": 77,
            "sku": "SLCTBS-65BF836D",
            "sku_id": 99,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 72,
                    "label": "XL",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 12,
                    "label": "Yellow",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 31,
            "product_id": 77,
            "sku": "SLCTBS-4B78DADB",
            "sku_id": 100,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 68,
                    "label": "XS",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 13,
                    "label": "Orange",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 32,
            "product_id": 77,
            "sku": "SLCTBS-4C827E7D",
            "sku_id": 101,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 69,
                    "label": "S",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 13,
                    "label": "Orange",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 33,
            "product_id": 77,
            "sku": "SLCTBS-D5AC2CA3",
            "sku_id": 102,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 70,
                    "label": "M",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 13,
                    "label": "Orange",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 34,
            "product_id": 77,
            "sku": "SLCTBS-3B1520F8",
            "sku_id": 103,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 1,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 71,
                    "label": "L",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 13,
                    "label": "Orange",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 35,
            "product_id": 77,
            "sku": "SLCTBS-99A2A51F",
            "sku_id": 104,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 72,
                    "label": "XL",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 13,
                    "label": "Orange",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 36,
            "product_id": 77,
            "sku": "SLCTBS-E90FEF02",
            "sku_id": 105,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 68,
                    "label": "XS",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 39,
                    "label": "Red",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 37,
            "product_id": 77,
            "sku": "SLCTBS-55462E47",
            "sku_id": 106,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 69,
                    "label": "S",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 39,
                    "label": "Red",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 38,
            "product_id": 77,
            "sku": "SLCTBS-A818A1D5",
            "sku_id": 107,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 1,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 70,
                    "label": "M",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 39,
                    "label": "Red",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 39,
            "product_id": 77,
            "sku": "SLCTBS-5A16741E",
            "sku_id": 108,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 3,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 71,
                    "label": "L",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 39,
                    "label": "Red",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 40,
            "product_id": 77,
            "sku": "SLCTBS-7A4493EA",
            "sku_id": 109,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 72,
                    "label": "XL",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 39,
                    "label": "Red",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 41,
            "product_id": 77,
            "sku": "SLCTBS-8E5DA4B2",
            "sku_id": 110,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 68,
                    "label": "XS",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 14,
                    "label": "Pink",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 42,
            "product_id": 77,
            "sku": "SLCTBS-440E68D3",
            "sku_id": 111,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 1,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 69,
                    "label": "S",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 14,
                    "label": "Pink",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 43,
            "product_id": 77,
            "sku": "SLCTBS-2D8DC13D",
            "sku_id": 112,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 70,
                    "label": "M",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 14,
                    "label": "Pink",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 44,
            "product_id": 77,
            "sku": "SLCTBS-70D1759E",
            "sku_id": 113,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 0,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 71,
                    "label": "L",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 14,
                    "label": "Pink",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        },
        {
            "id": 45,
            "product_id": 77,
            "sku": "SLCTBS-C17A7D36",
            "sku_id": 114,
            "price": null,
            "calculated_price": 49,
            "sale_price": null,
            "retail_price": null,
            "map_price": null,
            "weight": null,
            "calculated_weight": 1,
            "width": null,
            "height": null,
            "depth": null,
            "is_free_shipping": false,
            "fixed_cost_shipping_price": null,
            "purchasing_disabled": false,
            "purchasing_disabled_message": "",
            "image_url": "",
            "cost_price": 0,
            "upc": "",
            "mpn": "",
            "gtin": "",
            "inventory_level": 2,
            "inventory_warning_level": 0,
            "bin_picking_number": "0",
            "option_values": [
                {
                    "id": 72,
                    "label": "XL",
                    "option_id": 108,
                    "option_display_name": "Size"
                },
                {
                    "id": 14,
                    "label": "Pink",
                    "option_id": 109,
                    "option_display_name": "Color"
                }
            ]
        }
    ],
    "images": [
        {
            "id": 265,
            "product_id": 77,
            "is_thumbnail": false,
            "sort_order": 2,
            "description": "",
            "image_file": "%%SAMPLE%%/stencil/foglinenbeigestripetowel3b.jpg",
            "url_zoom": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/265/foglinenbeigestripetowel3b.1687821561.1280.1280.jpg?c=1",
            "url_standard": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/265/foglinenbeigestripetowel3b.1687821561.386.513.jpg?c=1",
            "url_thumbnail": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/265/foglinenbeigestripetowel3b.1687821561.220.290.jpg?c=1",
            "url_tiny": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/265/foglinenbeigestripetowel3b.1687821561.44.58.jpg?c=1",
            "date_modified": "2023-06-26T23:19:21+00:00"
        },
        {
            "id": 266,
            "product_id": 77,
            "is_thumbnail": true,
            "sort_order": 0,
            "description": "",
            "image_file": "%%SAMPLE%%/stencil/foglinenbeigestripetowel1b.jpg",
            "url_zoom": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/266/foglinenbeigestripetowel1b.1687821561.1280.1280.jpg?c=1",
            "url_standard": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/266/foglinenbeigestripetowel1b.1687821561.386.513.jpg?c=1",
            "url_thumbnail": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/266/foglinenbeigestripetowel1b.1687821561.220.290.jpg?c=1",
            "url_tiny": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/266/foglinenbeigestripetowel1b.1687821561.44.58.jpg?c=1",
            "date_modified": "2023-06-26T23:19:21+00:00"
        },
        {
            "id": 267,
            "product_id": 77,
            "is_thumbnail": false,
            "sort_order": 1,
            "description": "",
            "image_file": "%%SAMPLE%%/stencil/foglinenbeigestripetowel2b.jpg",
            "url_zoom": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/267/foglinenbeigestripetowel2b.1687821561.1280.1280.jpg?c=1",
            "url_standard": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/267/foglinenbeigestripetowel2b.1687821561.386.513.jpg?c=1",
            "url_thumbnail": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/267/foglinenbeigestripetowel2b.1687821561.220.290.jpg?c=1",
            "url_tiny": "https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/267/foglinenbeigestripetowel2b.1687821561.44.58.jpg?c=1",
            "date_modified": "2023-06-26T23:19:21+00:00"
        }
    ]
}
// ID

const test = {
    'id': 77, 
    'name': 'Fog Linen Chambray Towel - Beige Stripe', 
    'type': 'physical', 
    'sku': 'SLCTBS', 
    'description': '<p>The perfect beach towel: thin, lightweight and highly absorbent. Crafted by Fog Linen in Japan using soft Lithuanian linen, each towel rolls up for compact stowaway. Dry off after a refreshing dip in the ocean and stretch out on it for a sun bath. The thinness ensures a quick dry so you can have it rolled back up in your bag without soaking your belongings.</p>\n<p>Measures 75 x 145 cm/29.5 x 57 in</p>\n<p>100% Linen</p>', 
    'weight': 1, 
    'width': 0, 
    'depth': 0, 
    'height': 0, 
    'price': 49, 
    'cost_price': 0, 
    'retail_price': 0, 
    'sale_price': 0, 
    'map_price': 0, 
    'tax_class_id': 0, 
    'product_tax_code': '', 
    'calculated_price': 49, //
    'categories': [23, 18], 
    'brand_id': 36, 
    'option_set_id': 14, //
    'option_set_display': 'right', //
    'inventory_level': 43, 
    'inventory_warning_level': 0, 
    'inventory_tracking': 'variant', 
    'reviews_rating_sum': 0, //
    'reviews_count': 0, //
    'total_sold': 4, //
    'fixed_cost_shipping_price': 0, //
    'is_free_shipping': False, 
    'is_visible': True, 
    'is_featured': False, 
    'related_products': [-1], 
    'warranty': '', 
    'bin_picking_number': '', 
    'layout_file': 'product.html',
     'upc': '', 
     'mpn': '', 
     'gtin': '', 
     'search_keywords': '', 
     'availability': 'available', 
     'availability_description': '',
      'gift_wrapping_options_type': 'any', 
      'gift_wrapping_options_list': [], 
      'sort_order': 0, 'condition': 'New', 'is_condition_shown': False, 'order_quantity_minimum': 0, 'order_quantity_maximum': 0, 'page_title': 'Fog Linen Chambray Towel - Beige Stripe by Fog Linen', 'meta_keywords': 'Fog Linen Chambray Towel, Beige Stripe, beach towel, lightweight towel, absorbent towel, Fog Linen, Japan, Lithuanian linen', 'meta_description': 'Shop the Fog Linen Chambray Towel - Beige Stripe. Crafted by Fog Linen in Japan using soft Lithuanian linen, this thin and lightweight towel is perfect for the beach. Measures 75 x 145 cm/29.5 x 57 in. 100% Linen.', 'date_created': '2015-07-03T17:57:10+00:00', 'view_count': 63, 'preorder_release_date': None, 'preorder_message': '', 'is_preorder_only': False, 'is_price_hidden': False, 'price_hidden_label': '', 'custom_url': {'url': '/fog-linen-chambray-towel-beige-stripe/', 'is_customized': False}, 'base_variant_id': None, 'open_graph_type': 'product', 'open_graph_title': '', 'open_graph_description': '', 'open_graph_use_meta_description': True, 'open_graph_use_product_name': True, 'open_graph_use_image': True, 'variants': [{'id': 1, 'product_id': 77, 'sku': 'SLCTBS-A9615491', 'sku_id': 70, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 68, 'label': 'XS', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 7, 'label': 'Silver', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 2, 'product_id': 77, 'sku': 'SLCTBS-5596D19E', 'sku_id': 71, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 69, 'label': 'S', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 7, 'label': 'Silver', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 3, 'product_id': 77, 'sku': 'SLCTBS-08950B35', 'sku_id': 72, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 3, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 70, 'label': 'M', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 7, 'label': 'Silver', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 4, 'product_id': 77, 'sku': 'SLCTBS-7765C099', 'sku_id': 73, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 71, 'label': 'L', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 7, 'label': 'Silver', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 5, 'product_id': 77, 'sku': 'SLCTBS-FC402DAC', 'sku_id': 74, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 72, 'label': 'XL', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 7, 'label': 'Silver', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 6, 'product_id': 77, 'sku': 'SLCTBS-4404031B', 'sku_id': 75, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 68, 'label': 'XS', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 8, 'label': 'Black', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 7, 'product_id': 77, 'sku': 'SLCTBS-EBD25EBB', 'sku_id': 76, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 69, 'label': 'S', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 8, 'label': 'Black', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 8, 'product_id': 77, 'sku': 'SLCTBS-6C6855B4', 'sku_id': 77, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 70, 'label': 'M', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 8, 'label': 'Black', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 9, 'product_id': 77, 'sku': 'SLCTBS-2C8FBF3C', 'sku_id': 78, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 71, 'label': 'L', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 8, 'label': 'Black', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 10, 'product_id': 77, 'sku': 'SLCTBS-906CEB57', 'sku_id': 79, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 72, 'label': 'XL', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 8, 'label': 'Black', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 11, 'product_id': 77, 'sku': 'SLCTBS-B6062BD4', 'sku_id': 80, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 68, 'label': 'XS', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 9, 'label': 'Purple', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 12, 'product_id': 77, 'sku': 'SLCTBS-5819AF19', 'sku_id': 81, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 69, 'label': 'S', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 9, 'label': 'Purple', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 13, 'product_id': 77, 'sku': 'SLCTBS-E4DD8E16', 'sku_id': 82, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 70, 'label': 'M', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 9, 'label': 'Purple', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 14, 'product_id': 77, 'sku': 'SLCTBS-BC2B8DF2', 'sku_id': 83, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 71, 'label': 'L', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 9, 'label': 'Purple', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 15, 'product_id': 77, 'sku': 'SLCTBS-A588AB27', 'sku_id': 84, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 1, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 72, 'label': 'XL', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 9, 'label': 'Purple', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 16, 'product_id': 77, 'sku': 'SLCTBS-CCAEAE80', 'sku_id': 85, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 68, 'label': 'XS', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 10, 'label': 'Blue', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 17, 'product_id': 77, 'sku': 'SLCTBS-AA87E3C9', 'sku_id': 86, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 69, 'label': 'S', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 10, 'label': 'Blue', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 18, 'product_id': 77, 'sku': 'SLCTBS-7113955F', 'sku_id': 87, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 70, 'label': 'M', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 10, 'label': 'Blue', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 19, 'product_id': 77, 'sku': 'SLCTBS-AF6BD618', 'sku_id': 88, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 1, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 71, 'label': 'L', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 10, 'label': 'Blue', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 20, 'product_id': 77, 'sku': 'SLCTBS-3E102384', 'sku_id': 89, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 72, 'label': 'XL', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 10, 'label': 'Blue', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 21, 'product_id': 77, 'sku': 'SLCTBS-9D20C568', 'sku_id': 90, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 68, 'label': 'XS', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 11, 'label': 'Green', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 22, 'product_id': 77, 'sku': 'SLCTBS-ADB96FB6', 'sku_id': 91, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 69, 'label': 'S', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 11, 'label': 'Green', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 23, 'product_id': 77, 'sku': 'SLCTBS-DDB31DBA', 'sku_id': 92, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 70, 'label': 'M', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 11, 'label': 'Green', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 24, 'product_id': 77, 'sku': 'SLCTBS-1FB01D8C', 'sku_id': 93, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 1, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 71, 'label': 'L', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 11, 'label': 'Green', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 25, 'product_id': 77, 'sku': 'SLCTBS-15688F0B', 'sku_id': 94, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 72, 'label': 'XL', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 11, 'label': 'Green', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 26, 'product_id': 77, 'sku': 'SLCTBS-CB178380', 'sku_id': 95, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 68, 'label': 'XS', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 12, 'label': 'Yellow', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 27, 'product_id': 77, 'sku': 'SLCTBS-E8CD0FC8', 'sku_id': 96, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 1, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 69, 'label': 'S', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 12, 'label': 'Yellow', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 28, 'product_id': 77, 'sku': 'SLCTBS-E0F9565B', 'sku_id': 97, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 70, 'label': 'M', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 12, 'label': 'Yellow', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 29, 'product_id': 77, 'sku': 'SLCTBS-AC1B2718', 'sku_id': 98, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 71, 'label': 'L', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 12, 'label': 'Yellow', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 30, 'product_id': 77, 'sku': 'SLCTBS-65BF836D', 'sku_id': 99, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 72, 'label': 'XL', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 12, 'label': 'Yellow', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 31, 'product_id': 77, 'sku': 'SLCTBS-4B78DADB', 'sku_id': 100, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 68, 'label': 'XS', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 13, 'label': 'Orange', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 32, 'product_id': 77, 'sku': 'SLCTBS-4C827E7D', 'sku_id': 101, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 69, 'label': 'S', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 13, 'label': 'Orange', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 33, 'product_id': 77, 'sku': 'SLCTBS-D5AC2CA3', 'sku_id': 102, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 70, 'label': 'M', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 13, 'label': 'Orange', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 34, 'product_id': 77, 'sku': 'SLCTBS-3B1520F8', 'sku_id': 103, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 1, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 71, 'label': 'L', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 13, 'label': 'Orange', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 35, 'product_id': 77, 'sku': 'SLCTBS-99A2A51F', 'sku_id': 104, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 72, 'label': 'XL', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 13, 'label': 'Orange', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 36, 'product_id': 77, 'sku': 'SLCTBS-E90FEF02', 'sku_id': 105, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 68, 'label': 'XS', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 39, 'label': 'Red', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 37, 'product_id': 77, 'sku': 'SLCTBS-55462E47', 'sku_id': 106, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 69, 'label': 'S', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 39, 'label': 'Red', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 38, 'product_id': 77, 'sku': 'SLCTBS-A818A1D5', 'sku_id': 107, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 1, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 70, 'label': 'M', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 39, 'label': 'Red', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 39, 'product_id': 77, 'sku': 'SLCTBS-5A16741E', 'sku_id': 108, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 3, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 71, 'label': 'L', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 39, 'label': 'Red', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 40, 'product_id': 77, 'sku': 'SLCTBS-7A4493EA', 'sku_id': 109, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 72, 'label': 'XL', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 39, 'label': 'Red', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 41, 'product_id': 77, 'sku': 'SLCTBS-8E5DA4B2', 'sku_id': 110, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 68, 'label': 'XS', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 14, 'label': 'Pink', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 42, 'product_id': 77, 'sku': 'SLCTBS-440E68D3', 'sku_id': 111, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 1, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 69, 'label': 'S', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 14, 'label': 'Pink', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 43, 'product_id': 77, 'sku': 'SLCTBS-2D8DC13D', 'sku_id': 112, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 70, 'label': 'M', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 14, 'label': 'Pink', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 44, 'product_id': 77, 'sku': 'SLCTBS-70D1759E', 'sku_id': 113, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 0, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 71, 'label': 'L', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 14, 'label': 'Pink', 'option_id': 109, 'option_display_name': 'Color'}]}, {'id': 45, 'product_id': 77, 'sku': 'SLCTBS-C17A7D36', 'sku_id': 114, 'price': None, 'calculated_price': 49, 'sale_price': None, 'retail_price': None, 'map_price': None, 'weight': None, 'calculated_weight': 1, 'width': None, 'height': None, 'depth': None, 'is_free_shipping': False, 'fixed_cost_shipping_price': None, 'purchasing_disabled': False, 'purchasing_disabled_message': '', 'image_url': '', 'cost_price': 0, 'upc': '', 'mpn': '', 'gtin': '', 'inventory_level': 2, 'inventory_warning_level': 0, 'bin_picking_number': '0', 'option_values': [{'id': 72, 'label': 'XL', 'option_id': 108, 'option_display_name': 'Size'}, {'id': 14, 'label': 'Pink', 'option_id': 109, 'option_display_name': 'Color'}]}], 'images': [{'id': 265, 'product_id': 77, 'is_thumbnail': False, 'sort_order': 2, 'description': '', 'image_file': '%%SAMPLE%%/stencil/foglinenbeigestripetowel3b.jpg', 'url_zoom': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/265/foglinenbeigestripetowel3b.1687821561.1280.1280.jpg?c=1', 'url_standard': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/265/foglinenbeigestripetowel3b.1687821561.386.513.jpg?c=1', 'url_thumbnail': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/265/foglinenbeigestripetowel3b.1687821561.220.290.jpg?c=1', 'url_tiny': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/265/foglinenbeigestripetowel3b.1687821561.44.58.jpg?c=1', 'date_modified': '2023-06-26T23:19:21+00:00'}, {'id': 266, 'product_id': 77, 'is_thumbnail': True, 'sort_order': 0, 'description': '', 'image_file': '%%SAMPLE%%/stencil/foglinenbeigestripetowel1b.jpg', 'url_zoom': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/266/foglinenbeigestripetowel1b.1687821561.1280.1280.jpg?c=1', 'url_standard': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/266/foglinenbeigestripetowel1b.1687821561.386.513.jpg?c=1', 'url_thumbnail': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/266/foglinenbeigestripetowel1b.1687821561.220.290.jpg?c=1', 'url_tiny': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/266/foglinenbeigestripetowel1b.1687821561.44.58.jpg?c=1', 'date_modified': '2023-06-26T23:19:21+00:00'}, {'id': 267, 'product_id': 77, 'is_thumbnail': False, 'sort_order': 1, 'description': '', 'image_file': '%%SAMPLE%%/stencil/foglinenbeigestripetowel2b.jpg', 'url_zoom': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/267/foglinenbeigestripetowel2b.1687821561.1280.1280.jpg?c=1', 'url_standard': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/267/foglinenbeigestripetowel2b.1687821561.386.513.jpg?c=1', 'url_thumbnail': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/267/foglinenbeigestripetowel2b.1687821561.220.290.jpg?c=1', 'url_tiny': 'https://cdn11.bigcommerce.com/s-ordyxlzj4a/products/77/images/267/foglinenbeigestripetowel2b.1687821561.44.58.jpg?c=1', 'date_modified': '2023-06-26T23:19:21+00:00'}]}