# Generated by Django 3.2.5 on 2023-07-14 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_hash', models.CharField(max_length=16, unique=True)),
                ('access_token', models.CharField(max_length=128)),
                ('scope', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_id', models.IntegerField()),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metaMorphedApp.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metaMorphedApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='admin_storeuser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_user_admin', to='metaMorphedApp.storeuser'),
        ),
        migrations.AddField(
            model_name='store',
            name='storeusers',
            field=models.ManyToManyField(related_name='stores', to='metaMorphedApp.StoreUser'),
        ),
    ]
