# Generated by Django 3.2.5 on 2023-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaMorphedApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username_test', max_length=30),
            preserve_default=False,
        ),
    ]
