# Generated by Django 3.2.5 on 2023-08-28 03:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metaMorphedApp', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page_title', models.CharField(max_length=300)),
                ('meta_description', models.TextField()),
                ('meta_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metaMorphedApp.store')),
            ],
        ),
    ]
