# Generated by Django 3.2.5 on 2023-08-28 04:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaMorphedApp', '0003_producttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='additional_product_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='template_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
