# Generated by Django 3.2.5 on 2023-08-28 04:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaMorphedApp', '0004_auto_20230828_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='additional_product_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
    ]
