# Generated by Django 3.2.5 on 2023-08-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaMorphedApp', '0005_alter_producttemplate_additional_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='template_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
