# Generated by Django 3.2.5 on 2023-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaMorphedApp', '0006_alter_producttemplate_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='meta_keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='page_title',
            field=models.TextField(),
        ),
    ]
