# Generated by Django 3.2.5 on 2023-08-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaMorphedApp', '0007_auto_20230828_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='template_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='producttemplate',
            unique_together={('template_name', 'store')},
        ),
    ]
