# Generated by Django 3.2.5 on 2024-04-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaMorphedApp', '0008_auto_20230828_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='admin_storeuser_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='storeusers',
        ),
        migrations.AddField(
            model_name='store',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='access_token',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='StoreUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
