# Use an official Node runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the project code to the container
COPY . .

# Build the React app
RUN npm run build

# Expose the port the React app runs on
EXPOSE 3003

# Start the React app
CMD ["npm", "start"]